#!/bin/bash
 
#PBS -l select=1:ncpus=1:mem=124gb
#PBS -l walltime=11:59:59
#PBS -M Jason.Everett@unsw.edu.au
#PBS -m ae
#PBS -o JobOutput/
#PBS -e JobOutput/
#PBS -J 1-12
#PBS -j oe

module purge
module add r/4.2.2
module add udunits/2.2.28
module add netcdf-c/4.9.0
module add gdal/3.5.3-szip
module add proj/8.2.1
module add sqlite/3.39.4
module add geos/3.9.1
module add libspatialite/5.0.1

cd $PBS_O_WORKDIR

Rscript Calculate_ProbMatPTGlobalCompile.R
